### ISSUE TITLE
[non-facet data] add other / additional info for facilities

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#106] opened 2016-02-25 11:09 UTC
need to add an “other” space on the facilities information that shows when you expand the information for the results.  This will pull from an “other” column on the input spreadsheet. here we can put: special info like veterans only, children can live with parents, 3000 out of pocket etc.

**Comment by ronnorthrip** [comment] 2017-04-18 18:03
This is a duplicate of issue #133

**Closed as completed by ronnorthrip** 2017-04-18 18:03 UTC
Labels: help wanted, priority 2
